version: "3.7"
services:
  db:
    image: postgres:15
    container_name: booking_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    image: web
    build:
      context: .
    ports:
      - "8080:8080"
    command: ["/app/docker/web.sh"]

volumes:
  postgresdata: